/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin.index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin.users'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin.settings'
import { Route as AuthenticatedSuperAdminRolesRouteImport } from './routes/_authenticated/super-admin.roles'
import { Route as AuthenticatedSuperAdminHealthRouteImport } from './routes/_authenticated/super-admin.health'
import { Route as AuthenticatedSuperAdminFeaturesRouteImport } from './routes/_authenticated/super-admin.features'
import { Route as AuthenticatedSuperAdminBranchesRouteImport } from './routes/_authenticated/super-admin.branches'
import { Route as AuthenticatedSuperAdminAuditRouteImport } from './routes/_authenticated/super-admin.audit'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members.$id'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminTransfersRouteImport } from './routes/_authenticated/admin.transfers'
import { Route as AuthenticatedAdminHouseFellowshipRouteImport } from './routes/_authenticated/admin.house-fellowship'
import { Route as AuthenticatedAdminFamilyGroupsRouteImport } from './routes/_authenticated/admin.family-groups'
import { Route as AuthenticatedAdminDraftsRouteImport } from './routes/_authenticated/admin.drafts'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminFormsRegistrationFormRouteImport } from './routes/_authenticated/admin.forms.registration-form'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminRolesRoute =
  AuthenticatedSuperAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminHealthRoute =
  AuthenticatedSuperAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminFeaturesRoute =
  AuthenticatedSuperAdminFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminBranchesRoute =
  AuthenticatedSuperAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAuditRoute =
  AuthenticatedSuperAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTransfersRoute =
  AuthenticatedAdminTransfersRouteImport.update({
    id: '/admin/transfers',
    path: '/admin/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHouseFellowshipRoute =
  AuthenticatedAdminHouseFellowshipRouteImport.update({
    id: '/admin/house-fellowship',
    path: '/admin/house-fellowship',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFamilyGroupsRoute =
  AuthenticatedAdminFamilyGroupsRouteImport.update({
    id: '/admin/family-groups',
    path: '/admin/family-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDraftsRoute =
  AuthenticatedAdminDraftsRouteImport.update({
    id: '/admin/drafts',
    path: '/admin/drafts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFormsRegistrationFormRoute =
  AuthenticatedAdminFormsRegistrationFormRouteImport.update({
    id: '/admin/forms/registration-form',
    path: '/admin/forms/registration-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/admin/family-groups': typeof AuthenticatedAdminFamilyGroupsRoute
  '/admin/house-fellowship': typeof AuthenticatedAdminHouseFellowshipRoute
  '/admin/transfers': typeof AuthenticatedAdminTransfersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/super-admin/features': typeof AuthenticatedSuperAdminFeaturesRoute
  '/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/forms/registration-form': typeof AuthenticatedAdminFormsRegistrationFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/admin/family-groups': typeof AuthenticatedAdminFamilyGroupsRoute
  '/admin/house-fellowship': typeof AuthenticatedAdminHouseFellowshipRoute
  '/admin/transfers': typeof AuthenticatedAdminTransfersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/super-admin/features': typeof AuthenticatedSuperAdminFeaturesRoute
  '/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/forms/registration-form': typeof AuthenticatedAdminFormsRegistrationFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/_authenticated/admin/family-groups': typeof AuthenticatedAdminFamilyGroupsRoute
  '/_authenticated/admin/house-fellowship': typeof AuthenticatedAdminHouseFellowshipRoute
  '/_authenticated/admin/transfers': typeof AuthenticatedAdminTransfersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/_authenticated/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/_authenticated/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/_authenticated/super-admin/features': typeof AuthenticatedSuperAdminFeaturesRoute
  '/_authenticated/super-admin/health': typeof AuthenticatedSuperAdminHealthRoute
  '/_authenticated/super-admin/roles': typeof AuthenticatedSuperAdminRolesRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/admin/forms/registration-form': typeof AuthenticatedAdminFormsRegistrationFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/register'
    | '/unauthorized'
    | '/dashboard'
    | '/super-admin'
    | '/admin/departments'
    | '/admin/drafts'
    | '/admin/family-groups'
    | '/admin/house-fellowship'
    | '/admin/transfers'
    | '/admin/verifications'
    | '/members/$id'
    | '/super-admin/audit'
    | '/super-admin/branches'
    | '/super-admin/features'
    | '/super-admin/health'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/members/'
    | '/super-admin/'
    | '/admin/forms/registration-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/register'
    | '/unauthorized'
    | '/dashboard'
    | '/admin/departments'
    | '/admin/drafts'
    | '/admin/family-groups'
    | '/admin/house-fellowship'
    | '/admin/transfers'
    | '/admin/verifications'
    | '/members/$id'
    | '/super-admin/audit'
    | '/super-admin/branches'
    | '/super-admin/features'
    | '/super-admin/health'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/members'
    | '/super-admin'
    | '/admin/forms/registration-form'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kiosk'
    | '/register'
    | '/unauthorized'
    | '/_authenticated/dashboard'
    | '/_authenticated/super-admin'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/drafts'
    | '/_authenticated/admin/family-groups'
    | '/_authenticated/admin/house-fellowship'
    | '/_authenticated/admin/transfers'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/members/$id'
    | '/_authenticated/super-admin/audit'
    | '/_authenticated/super-admin/branches'
    | '/_authenticated/super-admin/features'
    | '/_authenticated/super-admin/health'
    | '/_authenticated/super-admin/roles'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/members/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/admin/forms/registration-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/roles': {
      id: '/_authenticated/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof AuthenticatedSuperAdminRolesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/health': {
      id: '/_authenticated/super-admin/health'
      path: '/health'
      fullPath: '/super-admin/health'
      preLoaderRoute: typeof AuthenticatedSuperAdminHealthRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/features': {
      id: '/_authenticated/super-admin/features'
      path: '/features'
      fullPath: '/super-admin/features'
      preLoaderRoute: typeof AuthenticatedSuperAdminFeaturesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/branches': {
      id: '/_authenticated/super-admin/branches'
      path: '/branches'
      fullPath: '/super-admin/branches'
      preLoaderRoute: typeof AuthenticatedSuperAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/audit': {
      id: '/_authenticated/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/transfers': {
      id: '/_authenticated/admin/transfers'
      path: '/admin/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AuthenticatedAdminTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/house-fellowship': {
      id: '/_authenticated/admin/house-fellowship'
      path: '/admin/house-fellowship'
      fullPath: '/admin/house-fellowship'
      preLoaderRoute: typeof AuthenticatedAdminHouseFellowshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/family-groups': {
      id: '/_authenticated/admin/family-groups'
      path: '/admin/family-groups'
      fullPath: '/admin/family-groups'
      preLoaderRoute: typeof AuthenticatedAdminFamilyGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/drafts': {
      id: '/_authenticated/admin/drafts'
      path: '/admin/drafts'
      fullPath: '/admin/drafts'
      preLoaderRoute: typeof AuthenticatedAdminDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forms/registration-form': {
      id: '/_authenticated/admin/forms/registration-form'
      path: '/admin/forms/registration-form'
      fullPath: '/admin/forms/registration-form'
      preLoaderRoute: typeof AuthenticatedAdminFormsRegistrationFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAuditRoute: typeof AuthenticatedSuperAdminAuditRoute
  AuthenticatedSuperAdminBranchesRoute: typeof AuthenticatedSuperAdminBranchesRoute
  AuthenticatedSuperAdminFeaturesRoute: typeof AuthenticatedSuperAdminFeaturesRoute
  AuthenticatedSuperAdminHealthRoute: typeof AuthenticatedSuperAdminHealthRoute
  AuthenticatedSuperAdminRolesRoute: typeof AuthenticatedSuperAdminRolesRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAuditRoute: AuthenticatedSuperAdminAuditRoute,
    AuthenticatedSuperAdminBranchesRoute: AuthenticatedSuperAdminBranchesRoute,
    AuthenticatedSuperAdminFeaturesRoute: AuthenticatedSuperAdminFeaturesRoute,
    AuthenticatedSuperAdminHealthRoute: AuthenticatedSuperAdminHealthRoute,
    AuthenticatedSuperAdminRolesRoute: AuthenticatedSuperAdminRolesRoute,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminDraftsRoute: typeof AuthenticatedAdminDraftsRoute
  AuthenticatedAdminFamilyGroupsRoute: typeof AuthenticatedAdminFamilyGroupsRoute
  AuthenticatedAdminHouseFellowshipRoute: typeof AuthenticatedAdminHouseFellowshipRoute
  AuthenticatedAdminTransfersRoute: typeof AuthenticatedAdminTransfersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedAdminFormsRegistrationFormRoute: typeof AuthenticatedAdminFormsRegistrationFormRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminDraftsRoute: AuthenticatedAdminDraftsRoute,
  AuthenticatedAdminFamilyGroupsRoute: AuthenticatedAdminFamilyGroupsRoute,
  AuthenticatedAdminHouseFellowshipRoute:
    AuthenticatedAdminHouseFellowshipRoute,
  AuthenticatedAdminTransfersRoute: AuthenticatedAdminTransfersRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedAdminFormsRegistrationFormRoute:
    AuthenticatedAdminFormsRegistrationFormRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
